timezone: America/New_York

paginate: 8
paginate_path: '/blog/:num'

excerpt_separator: <!--more-->

# own settings
name: gisellegk.github.io
domain: gisellegk.github.io
url: http://gisellegk.github.io
description: Giselle Koo Portfolio
copyright: 2016
author:
    name: Giselle Koo
    github_link: https://github.com/gisellegk

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
    values:
      layout: "project"

