timezone: America/New_York

# own settings
name: gisellegk.github.io
description: Giselle Koo Portfolio
copyright: 2017
author:
    name: Giselle Koo
    github_link: https://github.com/gisellegk

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "basic"
  -
    scope:
      path: "_projects"
    values:
      layout: "project"